name: yuannian-sync
on:
  schedule:
    - cron: '18 7 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-yuannian1112-jd_scripts.
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.FIS }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync yuannian1112-jd_scripts.
        uses: repo-sync/github-sync@v2
        if: env.FIS
        with:
          source_repo: "https://github.com/yuannian1112/jd_scripts.git"
          source_branch: "master"
          destination_branch: "yuannian"
          github_token: ${{ secrets.FIS }}
